# Generated by Django 5.2.17 on 2026-08-31 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recoverycode',
            new_name='identity_re_user_id_57bdc9_idx',
            old_name='identity_re_user_id_9bb5ef_idx',
        ),
    ]
