# Generated by Django 5.2.17 on 2026-09-01 02:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plant_code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=24)),
                ('address_line_1', models.CharField(blank=True, max_length=180)),
                ('address_line_2', models.CharField(blank=True, max_length=180)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='capacity_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='postal_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=24),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='warehouse.plant'),
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_type_code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=24)),
                ('capacity_rules', models.JSONField(blank=True, default=dict)),
                ('handling_rules', models.JSONField(blank=True, default=dict)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_types', to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('zone_type', models.CharField(choices=[('RECEIVING', 'Receiving'), ('STAGING', 'Staging'), ('QA', 'QA'), ('QUARANTINE', 'Quarantine'), ('STORAGE', 'Storage'), ('PICKING', 'Picking'), ('PACKING', 'Packing'), ('DISPATCH', 'Dispatch'), ('RETURNS', 'Returns'), ('DAMAGED', 'Damaged'), ('BLOCKED', 'Blocked'), ('CUSTOM', 'Custom')], default='STORAGE', max_length=24)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=24)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StorageSection',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=24)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='warehouse.warehouse')),
                ('storage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='warehouse.storagetype')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='warehouse.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bin_code', models.CharField(max_length=80)),
                ('barcode', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=24)),
                ('aisle', models.CharField(blank=True, max_length=40)),
                ('bay', models.CharField(blank=True, max_length=40)),
                ('level', models.CharField(blank=True, max_length=40)),
                ('position', models.CharField(blank=True, max_length=40)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('max_volume', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('max_hu_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_pickable', models.BooleanField(default=True)),
                ('is_putaway_allowed', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_countable', models.BooleanField(default=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bins', to='warehouse.warehouse')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bins', to='warehouse.storagesection')),
                ('storage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bins', to='warehouse.storagetype')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bins', to='warehouse.zone')),
            ],
        ),
        migrations.AddConstraint(
            model_name='storagetype',
            constraint=models.UniqueConstraint(fields=('warehouse', 'storage_type_code'), name='unique_storage_type_code_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('warehouse', 'zone_code'), name='unique_zone_code_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='storagesection',
            constraint=models.UniqueConstraint(fields=('warehouse', 'section_code'), name='unique_section_code_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='bin',
            constraint=models.UniqueConstraint(fields=('warehouse', 'bin_code'), name='unique_bin_code_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='bin',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('warehouse', 'barcode'), name='unique_bin_barcode_per_warehouse'),
        ),
    ]
