from django.urls import path

from tenancy.views import (
    TenantContextView,
    TenantPermissionsView,
    TenantProbeView,
    TenantRolesView,
    TenantSettingsView,
    TenantUserDetailView,
    TenantUsersView,
    TenantWarehouseAssignmentsView,
)
from warehouse.views import (
    ActiveWarehouseContextView,
    BayDetailView,
    BayBulkView,
    BayExportView,
    BayImportView,
    BayListCreateView,
    BinDetailView,
    BinListCreateView,
    ContainerDetailView,
    ContainerListCreateView,
    HierarchyTreeView,
    HoldingUnitDetailView,
    HoldingUnitListCreateView,
    InventoryCategoryDetailView,
    InventoryCategoryListCreateView,
    MachineDetailView,
    MachineListCreateView,
    MissionDefinitionDetailView,
    MissionDefinitionListCreateView,
    MissionGroupDetailView,
    MissionGroupListCreateView,
    OperationDefinitionDetailView,
    OperationDefinitionListCreateView,
    PalletDetailView,
    PalletListCreateView,
    PeopleResourceDetailView,
    PeopleResourceListCreateView,
    PlantDetailView,
    PlantListCreateView,
    ProductCategoryDetailView,
    ProductCategoryListCreateView,
    SequenceDetailView,
    SequenceListCreateView,
    SequenceActionView,
    SkuGroupingDetailView,
    SkuGroupingListCreateView,
    StatusDefinitionDetailView,
    StatusDefinitionListCreateView,
    StorageSectionDetailView,
    StorageSectionListCreateView,
    StorageTypeDetailView,
    StorageTypeListCreateView,
    TenantDashboardView,
    TruckDetailView,
    TruckListCreateView,
    VehicleDetailView,
    VehicleListCreateView,
    WarehouseControlDetailView,
    WarehouseControlListCreateView,
    WarehouseDetailView,
    WarehouseListCreateView,
    ZoneDetailView,
    ZoneListCreateView,
    ZoneQueueDetailView,
    ZoneQueueListCreateView,
)

urlpatterns = [
    path("context/", TenantContextView.as_view(), name="tenant-context"),
    path("dashboard/", TenantDashboardView.as_view(), name="tenant-dashboard"),
    path("users/", TenantUsersView.as_view(), name="tenant-users"),
    path("users/<uuid:membership_id>/", TenantUserDetailView.as_view(), name="tenant-user-detail"),
    path("roles/", TenantRolesView.as_view(), name="tenant-roles"),
    path("permissions/", TenantPermissionsView.as_view(), name="tenant-permissions"),
    path("warehouse-assignments/", TenantWarehouseAssignmentsView.as_view(), name="tenant-warehouse-assignments"),
    path("settings/", TenantSettingsView.as_view(), name="tenant-settings"),
    path("context/warehouse/", ActiveWarehouseContextView.as_view(), name="tenant-active-warehouse"),
    path("hierarchy/", HierarchyTreeView.as_view(), name="tenant-hierarchy"),
    path("plants/", PlantListCreateView.as_view(), name="tenant-plants"),
    path("plants/<uuid:item_id>/", PlantDetailView.as_view(), name="tenant-plant-detail"),
    path("product-categories/", ProductCategoryListCreateView.as_view(), name="tenant-product-categories"),
    path("product-categories/<uuid:item_id>/", ProductCategoryDetailView.as_view(), name="tenant-product-category-detail"),
    path("warehouses/", WarehouseListCreateView.as_view(), name="tenant-warehouses"),
    path("warehouses/<uuid:item_id>/", WarehouseDetailView.as_view(), name="tenant-warehouse-detail"),
    path("zones/", ZoneListCreateView.as_view(), name="tenant-zones"),
    path("zones/<uuid:item_id>/", ZoneDetailView.as_view(), name="tenant-zone-detail"),
    path("storage-types/", StorageTypeListCreateView.as_view(), name="tenant-storage-types"),
    path("storage-types/<uuid:item_id>/", StorageTypeDetailView.as_view(), name="tenant-storage-type-detail"),
    path("storage-sections/", StorageSectionListCreateView.as_view(), name="tenant-storage-sections"),
    path("storage-sections/<uuid:item_id>/", StorageSectionDetailView.as_view(), name="tenant-storage-section-detail"),
    path("bays/", BayListCreateView.as_view(), name="tenant-bays"),
    path("bays/bulk/", BayBulkView.as_view(), name="tenant-bay-bulk"),
    path("bays/import/", BayImportView.as_view(), name="tenant-bay-import"),
    path("bays/export/", BayExportView.as_view(), name="tenant-bay-export"),
    path("bays/<uuid:item_id>/", BayDetailView.as_view(), name="tenant-bay-detail"),
    path("bins/", BinListCreateView.as_view(), name="tenant-bins"),
    path("bins/<uuid:item_id>/", BinDetailView.as_view(), name="tenant-bin-detail"),
    path("configuration/holding-units/", HoldingUnitListCreateView.as_view(), name="tenant-holding-units"),
    path("configuration/holding-units/<uuid:item_id>/", HoldingUnitDetailView.as_view(), name="tenant-holding-unit-detail"),
    path("configuration/pallets/", PalletListCreateView.as_view(), name="tenant-pallets"),
    path("configuration/pallets/<uuid:item_id>/", PalletDetailView.as_view(), name="tenant-pallet-detail"),
    path("configuration/machines/", MachineListCreateView.as_view(), name="tenant-machines"),
    path("configuration/machines/<uuid:item_id>/", MachineDetailView.as_view(), name="tenant-machine-detail"),
    path("configuration/resources/", PeopleResourceListCreateView.as_view(), name="tenant-resources"),
    path("configuration/resources/<uuid:item_id>/", PeopleResourceDetailView.as_view(), name="tenant-resource-detail"),
    path("configuration/sku-groups/", SkuGroupingListCreateView.as_view(), name="tenant-sku-groups"),
    path("configuration/sku-groups/<uuid:item_id>/", SkuGroupingDetailView.as_view(), name="tenant-sku-group-detail"),
    path("configuration/inventory-categories/", InventoryCategoryListCreateView.as_view(), name="tenant-inventory-categories"),
    path("configuration/inventory-categories/<uuid:item_id>/", InventoryCategoryDetailView.as_view(), name="tenant-inventory-category-detail"),
    path("configuration/operations/", OperationDefinitionListCreateView.as_view(), name="tenant-operations"),
    path("configuration/operations/<uuid:item_id>/", OperationDefinitionDetailView.as_view(), name="tenant-operation-detail"),
    path("configuration/missions/", MissionDefinitionListCreateView.as_view(), name="tenant-missions"),
    path("configuration/missions/<uuid:item_id>/", MissionDefinitionDetailView.as_view(), name="tenant-mission-detail"),
    path("configuration/mission-groups/", MissionGroupListCreateView.as_view(), name="tenant-mission-groups"),
    path("configuration/mission-groups/<uuid:item_id>/", MissionGroupDetailView.as_view(), name="tenant-mission-group-detail"),
    path("configuration/zone-queues/", ZoneQueueListCreateView.as_view(), name="tenant-zone-queues"),
    path("configuration/zone-queues/<uuid:item_id>/", ZoneQueueDetailView.as_view(), name="tenant-zone-queue-detail"),
    path("configuration/sequences/", SequenceListCreateView.as_view(), name="tenant-sequences"),
    path("configuration/sequences/<uuid:item_id>/<slug:action>/", SequenceActionView.as_view(), name="tenant-sequence-action"),
    path("configuration/sequences/<uuid:item_id>/", SequenceDetailView.as_view(), name="tenant-sequence-detail"),
    path("configuration/statuses/", StatusDefinitionListCreateView.as_view(), name="tenant-statuses"),
    path("configuration/statuses/<uuid:item_id>/", StatusDefinitionDetailView.as_view(), name="tenant-status-detail"),
    path("configuration/warehouse-control/", WarehouseControlListCreateView.as_view(), name="tenant-warehouse-control"),
    path("configuration/warehouse-control/<uuid:item_id>/", WarehouseControlDetailView.as_view(), name="tenant-warehouse-control-detail"),
    path("configuration/transport/trucks/", TruckListCreateView.as_view(), name="tenant-trucks"),
    path("configuration/transport/trucks/<uuid:item_id>/", TruckDetailView.as_view(), name="tenant-truck-detail"),
    path("configuration/transport/containers/", ContainerListCreateView.as_view(), name="tenant-containers"),
    path("configuration/transport/containers/<uuid:item_id>/", ContainerDetailView.as_view(), name="tenant-container-detail"),
    path("configuration/transport/vehicles/", VehicleListCreateView.as_view(), name="tenant-vehicles"),
    path("configuration/transport/vehicles/<uuid:item_id>/", VehicleDetailView.as_view(), name="tenant-vehicle-detail"),
    path("probe/", TenantProbeView.as_view(), name="tenant-probe"),
]
