# Generated by Django 5.2.17 on 2026-09-03 22:36

import control.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_tenantdomain_verification_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('dependencies', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OwnerNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('TENANT_PROVISIONING_FAILED', 'Tenant provisioning failed'), ('TENANT_DB_UNHEALTHY', 'Tenant database unhealthy'), ('BACKUP_FAILED', 'Backup failed'), ('MIGRATION_FAILED', 'Migration failed'), ('LICENSE_EXPIRING', 'License expiring'), ('SUBSCRIPTION_EXPIRING', 'Subscription expiring'), ('SUSPICIOUS_LOGIN', 'Suspicious login'), ('MFA_NON_COMPLIANT', 'MFA non-compliant'), ('SUPPORT_ACCESS_REQUEST', 'Support access request')], max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(max_length=280)),
                ('source_type', models.CharField(blank=True, max_length=80)),
                ('source_id', models.CharField(blank=True, max_length=120)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='featureflag',
            name='environment_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='plan',
            name='api_limit_per_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_interval',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=24),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='feature_entitlements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plan',
            name='storage_limit_gb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='support_tier',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='plan',
            name='user_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='warehouse_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renews_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=24),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantfeatureflag',
            name='override_state',
            field=models.CharField(choices=[('INHERIT', 'Inherit'), ('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], default='INHERIT', max_length=24),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='source',
            field=models.CharField(choices=[('PLAN', 'Plan'), ('OVERRIDE', 'Override')], default='OVERRIDE', max_length=24),
        ),
        migrations.CreateModel(
            name='BackupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='NOT_CONFIGURED', max_length=80)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('enabled', models.BooleanField(default=False)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_policy', to='control.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='NOT_CONFIGURED', max_length=80)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('WARNING', 'Warning'), ('FAILED', 'Failed'), ('NOT_CONFIGURED', 'Not configured')], default='NOT_CONFIGURED', max_length=24)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('safe_error_summary', models.CharField(blank=True, max_length=240)),
                ('restore_point_reference', models.CharField(blank=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_records', to='control.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(default=control.models.generate_license_number, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRING', 'Expiring'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=24)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control.plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='license', to='control.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestoreRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PREPARING', 'Preparing'), ('RESTORING', 'Restoring'), ('VERIFYING', 'Verifying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='REQUESTED', max_length=24)),
                ('safe_error_summary', models.CharField(blank=True, max_length=240)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_restore_requests', to=settings.AUTH_USER_MODEL)),
                ('backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control.backuprecord')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restore_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restore_requests', to='control.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
