# Generated by Django 5.2.17 on 2026-09-04 00:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_moduledefinition_ownernotification_platformsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdatabase',
            name='provisioning_step',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DATABASE_CREATING', 'Database creating'), ('DATABASE_CREATED', 'Database created'), ('ROLE_CREATED', 'Role created'), ('MIGRATING', 'Migrating'), ('CONFIGURING', 'Configuring'), ('ADMIN_INVITING', 'Admin inviting'), ('HEALTH_CHECKING', 'Health checking'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=40),
        ),
        migrations.AddField(
            model_name='tenantdatabase',
            name='safe_error_summary',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='override_state',
            field=models.CharField(choices=[('INHERIT', 'Inherit'), ('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], default='ENABLED', max_length=24),
        ),
        migrations.CreateModel(
            name='TenantConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('language', models.CharField(default='en', max_length=16)),
                ('enabled_module_defaults', models.JSONField(blank=True, default=list)),
                ('security_policy', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=24)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='control.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantModuleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_code', models.SlugField(max_length=80)),
                ('previous_state', models.CharField(blank=True, max_length=24)),
                ('new_state', models.CharField(max_length=24)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_history', to='control.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantAdminInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='PENDING', max_length=24)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_invitations', to='control.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_admin_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'email', 'status'], name='control_ten_tenant__55caf5_idx')],
            },
        ),
    ]
