# Generated by Django 5.2.17 on 2026-09-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_tenantdatabase_provisioning_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
