# Generated by Django 5.2.17 on 2026-09-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_plan_currency_plan_price_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflag',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
